repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-json
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: check-xml
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: flake8
      args: ['--exclude=docs/*,*migrations*,manage.py', '--ignore=E501,E731,E722,F841']
