# Generated by Django 2.1.7 on 2019-03-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_especies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrangencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrangencia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LocalRemocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_remocao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Preparacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparacao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TaxasPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxas_pagar', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=30)),
            ],
        ),
    ]
