# Generated by Django 2.1.7 on 2019-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190326_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='local_sep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='local_vel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
