# Generated by Django 2.1.7 on 2019-03-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alimentacao_cafe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alimentacao',
            new_name='Servico',
        ),
    ]
