# Generated by Django 2.1.7 on 2019-03-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funeraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalRemocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('local', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('falecido', models.CharField(max_length=50)),
                ('cpf_falecido', models.CharField(max_length=50)),
                ('especie', models.CharField(choices=[('convencional', 'Convencional'), ('falta_falecer', 'Falta Falecer'), ('iml', 'IML')], default='convencional', max_length=12)),
                ('abrangencia', models.CharField(choices=[('servico_completo', 'Servico Funerário Completo'), ('apenas_coroa_arranjos', 'Apenas Coroa e Arranjos')], default='servico_completo', max_length=22)),
                ('codigo', models.IntegerField()),
                ('urna', models.IntegerField()),
                ('biblia', models.BooleanField()),
                ('cristo', models.BooleanField()),
                ('sem_adereco', models.BooleanField()),
                ('veu', models.BooleanField()),
                ('obs_ornamentacao', models.CharField(max_length=50)),
                ('local_velorio', models.CharField(blank=True, max_length=100, null=True)),
                ('local_sepultamento', models.CharField(blank=True, max_length=100, null=True)),
                ('previsao_velorio', models.DateTimeField(blank=True, null=True)),
                ('data_sepultamento', models.DateTimeField(blank=True, null=True)),
                ('inicio_remocao', models.DateTimeField(blank=True, null=True)),
                ('termino_remocao', models.DateTimeField(blank=True, null=True)),
                ('inicio_urna', models.DateTimeField(blank=True, null=True)),
                ('termino_urna', models.DateTimeField(blank=True, null=True)),
                ('inicio_ctp', models.DateTimeField(blank=True, null=True)),
                ('termino_ctp', models.DateTimeField(blank=True, null=True)),
                ('inicio_cto', models.DateTimeField(blank=True, null=True)),
                ('termino_cto', models.DateTimeField(blank=True, null=True)),
                ('inicio_exp', models.DateTimeField(blank=True, null=True)),
                ('termino_exp', models.DateTimeField(blank=True, null=True)),
                ('inicio_cafe', models.DateTimeField(blank=True, null=True)),
                ('termino_cafe', models.DateTimeField(blank=True, null=True)),
                ('inicio_flora', models.DateTimeField(blank=True, null=True)),
                ('termino_flora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ornamentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preparacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxaPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('taxa', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cafe', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tipo_servico', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.TipoCafe'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='funeraria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.Funeraria'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ornamentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.Ornamentacao'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='preparacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.Preparacao'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='remocao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.LocalRemocao'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='taxas_apagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.TaxaPagar'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.TipoServico'),
        ),
    ]
