# Generated by Django 2.1.7 on 2019-03-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('executando', 'Executando'), ('fechado', 'Fechado')], default='aberto', max_length=22),
        ),
    ]
