# Generated by Django 2.1.3 on 2019-04-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funeraria',
            old_name='fun_endereco',
            new_name='endereco',
        ),
        migrations.RemoveField(
            model_name='funeraria',
            name='fun_razao_social',
        ),
        migrations.AddField(
            model_name='funeraria',
            name='razao_social',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
