# Generated by Django 2.1.7 on 2019-04-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0002_ordemservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='especie',
            field=models.CharField(choices=[('convencional', 'Convencional'), ('falta_falecer', 'Falta Falecer'), ('iml', 'IML')], default='convencional', max_length=14),
        ),
    ]
