# Generated by Django 2.1.7 on 2019-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0003_auto_20190401_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeraria',
            name='fun_endereco',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funeraria',
            name='fun_razao_social',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
