# Generated by Django 2.0 on 2019-04-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_areasetor_filial_setor'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('data_criacao', models.DateField()),
                ('assunto', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=500)),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
                ('setor_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Setor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
