# Generated by Django 2.1.3 on 2019-04-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('core', '0002_auto_20190412_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObitosHospitais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('data_falecimento', models.DateField()),
                ('nome_falecido', models.CharField(max_length=100)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('tel_responsavel', models.CharField(max_length=30)),
                ('motivo_nao_atendimento', models.CharField(choices=[('plano', 'Já possui plano'), ('concorrencia', 'Optou por outra empresa'), ('gratuidade', 'Gratuidade'), ('motivo_nao_informado', 'Motivo não informado')], default='motivo_nao_informado', max_length=50)),
                ('nome_atendente', models.CharField(max_length=100)),
                ('funeraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FunerariasMercado')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hospitais')),
                ('nome_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
