# Generated by Django 2.1.7 on 2019-03-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_abrangencia_localremocao_preparacao_taxaspagar_tiposervico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localremocao',
            name='local_remocao',
            field=models.CharField(max_length=40),
        ),
    ]
