# Generated by Django 2.1.7 on 2019-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190326_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falecido', models.CharField(max_length=50)),
                ('especie', models.ForeignKey(on_delete='', to='core.Especies')),
            ],
        ),
    ]
