# Generated by Django 2.1.7 on 2019-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funerarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funeraria', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='abrangencia',
            field=models.ForeignKey(default=1, on_delete='', to='core.Abrangencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='taxas_apagar',
            field=models.ForeignKey(default=1, on_delete='', to='core.TaxasPagar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete='', to='core.TipoServico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='funeraria',
            field=models.ForeignKey(default=1, on_delete='', to='core.Funerarias'),
            preserve_default=False,
        ),
    ]
