# Generated by Django 2.1.7 on 2019-03-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190326_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ornamentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ornamentacao', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='data_sep',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='obs_ornamentacao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='preparacao',
            field=models.ForeignKey(default=1, on_delete='', to='core.Preparacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='prev_vel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='ornamentacao',
            field=models.ForeignKey(default=1, on_delete='', to='core.Ornamentacao'),
            preserve_default=False,
        ),
    ]
