# Generated by Django 2.1.7 on 2019-03-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190326_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentacao',
            name='i_cafe',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='i_cto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='i_ctp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='i_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='i_flora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='i_rem',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='i_urna',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='t_cafe',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='t_cto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='t_ctp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='t_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='t_flora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='t_rem',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='t_urna',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preparacao',
            name='preparacao',
            field=models.CharField(max_length=50),
        ),
    ]
