# Generated by Django 2.1.7 on 2019-03-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190328_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalista',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='movmensalista',
            name='mensalista',
        ),
        migrations.RemoveField(
            model_name='movrotativo',
            name='veiculo',
        ),
        migrations.DeleteModel(
            name='Parametros',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Mensalista',
        ),
        migrations.DeleteModel(
            name='MovMensalista',
        ),
        migrations.DeleteModel(
            name='MovRotativo',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
