# Generated by Django 2.1.7 on 2019-03-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
