# Generated by Django 2.1.3 on 2019-04-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordem_servico', '0001_initial'),
        ('usuario', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantidade', models.IntegerField()),
                ('data_cotando', models.DateTimeField(blank=True, null=True)),
                ('data_disponivel', models.DateTimeField(blank=True, null=True)),
                ('data_finalizado', models.DateTimeField(blank=True, null=True)),
                ('status_atual', models.CharField(choices=[('aberto', 'Aberto'), ('cotando', 'Em Cotação'), ('disponivel', 'Disponível para retirada'), ('finalizado', 'Finalizado'), ('naoatendido', 'Não atendido')], default='aberto', max_length=22)),
                ('funeraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.Funeraria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produtos')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
