# Generated by Django 2.2 on 2019-04-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190412_1311'),
        ('pedido_material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomaterial',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedidomaterial',
            name='quantidade',
        ),
        migrations.CreateModel(
            name='PedidoMaterialProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('pedido_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='pedido_material.PedidoMaterial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.Produtos')),
            ],
        ),
    ]
