# Generated by Django 2.1.7 on 2019-04-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190401_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20),
        ),
    ]
