# Generated by Django 2.1.3 on 2019-04-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('descricao', models.CharField(max_length=15)),
                ('sigla', models.CharField(choices=[('caixa', 'Cx'), ('unidade', 'Un'), ('fardo', 'Fd'), ('pacote', 'Pct')], default='unidade', max_length=22)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('descricao', models.CharField(max_length=40)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Medida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
